apiVersion: apps/v1
kind: Deployment
metadata:
 name: mavenwebappdeployment
spec:
 replicas: 1
 strategy: 
    type: Recreate
 selector: 
   matchLabels: 
     app: mavenwebapp
 template:
  metadata:
   name: mavenwebapppod
   labels:
     app: mavenwebapp	 
  spec: 
    containers:
    - name: mavenwebapp
      image: bharath0812/spring:17.0
      ports:
      - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
 name: webapp
spec:
 type: NodePort
 selector:
   app: mavenwebapp	
 ports:
   - port: 8082
     targetPort: 8080
     nodePort: 32140
     protocol: TCP
